/* Generated by tools/sync-version.js -- DO NOT EDIT BY HAND.
 * Source of truth: <repo root>/VERSION  (bare version, no leading "v").
 * Regenerate with: node tools/sync-version.js
 *
 * ASCII only on purpose: MSVC warns C4819 when a source file has characters that the
 * active code page cannot represent, and this file is machine-written anyway.
 */
#ifndef DLSS5NR_VERSION_H
#define DLSS5NR_VERSION_H

#define APP_VERSION_W L"v2.0-anyway"

#endif /* DLSS5NR_VERSION_H */
